FROM jenkins/jenkins:lts

USER root

# Install Ansible and dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    apt-get clean

USER jenkins
